### ISSUE TITLE
Allow user to configure the DataManager stack they want to run

### ISSUE THREAD

**Issue by j6k4m8** [aplbrain/bossphorus#11]
I'm thinking we should make the binary configurable in a file, but with sane defaults. Something like:

`config.yml`
```yml
port: 8090
cache: "LRU"

usage_manager: "console"

data_managers:

    - ChunkedFileDataManager:
        upload_path: "uploads/"
    
    - BossDBRelayDataManager:
        host:        "bossdb.io"
        protocol:    "https"
        token:       "public"
```

And callable with `bossphorus --config config.yml`

In particular, I think being able to specify which data managers are used and in which order is something users may want to be able to do at runtime, which is perhaps a bit more complicated than the current env-variable technique allows. 

@movestill thoughts?
